name: Feature to Develop PR Checks

on:
  pull_request:
    branches:
      - develop
    types: [opened, synchronize, reopened]

jobs:
  validate:
    name: Validate Code
    runs-on: ubuntu-latest
    env:
      # Add ENVs
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv pip install -e . --system
          uv pip install pytest pytest-asyncio pytest-cov ruff --system

      - name: Run linting
        run: |
          ruff check --fix --extend-select=ARG,T201,TRY002,TRY400,C90
          ruff format

      - name: Run tests
        run: |
          pytest tests/ --cov=app --cov-report=xml --cov-report=term-missing:skip-covered | tee pytest-coverage.txt

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
