#https://docs.astral.sh/uv/getting-started/
[project]
name = "projectName"
version = "0.1.0"
description = "project description"
readme = "README.md"
requires-python = ">= 3.12"
dependencies = [
    "pre-commit>=4.1.0",
]
